# Generated by Django 6.1.1 on 2026-09-28 19:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='APEX Dual-Performance Copilot', max_length=150)),
                ('persona_name', models.CharField(default='Coach Alex (Elite Student-Athlete Strategist)', max_length=150)),
                ('tone', models.CharField(default='chic-coach', max_length=50)),
                ('system_prompt', models.TextField(default='You are APEX, an elite AI Agent and executive copilot engineered specifically for student-athletes. Your mission is to synergize rigorous academic excellence (GPA optimization, active recall study blocks, assignment workflows) with championship athletic performance (training load management, periodized nutrition, HRV recovery readiness, fatigue mitigation). Communicate with a sharp, inspiring, professionally chic tone. Be proactive, analytical, and structured.')),
                ('custom_directives', models.TextField(blank=True, default='1. Always prioritize injury prevention and recovery if fatigue is high.\n2. Balance heavy exam days with lower athletic volume.\n3. Recommend high-protein nutrient timing around workouts.')),
                ('target_audience', models.CharField(default='Collegiate & High-Performance Student-Athletes', max_length=100)),
                ('model_provider', models.CharField(default='local_simulation', max_length=50)),
                ('model_name', models.CharField(default='gemini-2.5-flash', max_length=100)),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('temperature', models.FloatField(default=0.7)),
                ('memory_limit', models.IntegerField(default=20)),
                ('active_tools', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AthleteStudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Alex Morgan Vance', max_length=150)),
                ('university', models.CharField(default='AAST Elite Technology & Athletics', max_length=200)),
                ('academic_major', models.CharField(default='Computer Engineering & Data Science', max_length=150)),
                ('sport', models.CharField(default='Track & Field / Sprinting (200m & 400m)', max_length=100)),
                ('position_event', models.CharField(default='Lead Anchor / 400m Dash', max_length=100)),
                ('current_gpa', models.FloatField(default=3.88)),
                ('target_gpa', models.FloatField(default=4.0)),
                ('weekly_training_hours', models.FloatField(default=16.5)),
                ('sleep_target_hours', models.FloatField(default=8.5)),
                ('recovery_readiness_score', models.IntegerField(default=91)),
                ('nutrition_preference', models.CharField(default='High-Carb Athletic Fueling & Clean Protein', max_length=150)),
                ('daily_calorie_target', models.IntegerField(default=3100)),
                ('daily_protein_target', models.IntegerField(default=160)),
                ('primary_goals', models.TextField(default="1. Break personal best in 400m sprint (sub-46.5s).\n2. Score straight A's in Advanced Algorithms & Operating Systems.\n3. Master sleep hygiene and prevent late-semester burnout.")),
                ('avatar_url', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('title', models.CharField(default='Academic-Athletic Synergy Session', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('sleep_hours', models.FloatField(default=8.2)),
                ('sleep_quality', models.IntegerField(default=88)),
                ('fatigue_level', models.IntegerField(default=22)),
                ('muscle_soreness', models.IntegerField(default=28)),
                ('training_strain', models.FloatField(default=14.5)),
                ('study_focus_hours', models.FloatField(default=5.2)),
                ('readiness_score', models.IntegerField(default=91)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('academic_class', 'Academic Lecture / Lab'), ('academic_study', 'Deep Study Block'), ('athletic_training', 'Athletic Training / Gym'), ('athletic_game', 'Competition / Match'), ('recovery_nutrition', 'Recovery & Nutrition'), ('personal', 'Personal & Rest')], default='academic_class', max_length=50)),
                ('day_of_week', models.CharField(default='Monday', max_length=20)),
                ('start_time', models.CharField(default='09:00', max_length=10)),
                ('end_time', models.CharField(default='10:30', max_length=10)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('ai_suggested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.CharField(default=uuid.uuid4, max_length=100)),
                ('workflow_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('triggered_by', models.CharField(default='user', max_length=50)),
                ('steps', models.JSONField(default=list)),
                ('summary_output', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], default='user', max_length=20)),
                ('message_type', models.CharField(default='chat', max_length=30)),
                ('content', models.TextField()),
                ('tool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tool_args', models.JSONField(blank=True, null=True)),
                ('tool_output', models.JSONField(blank=True, null=True)),
                ('thought_steps', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent_api.conversation')),
            ],
        ),
    ]
