# Generated by Django 6.1.1 on 2026-09-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0002_agentconversation_agentmessage_athleteprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='development_access_password',
            field=models.CharField(default='dev2026', max_length=128),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='internal_access_password',
            field=models.CharField(default='grad2026', max_length=128),
        ),
    ]
